### PR TITLE
Feature main page

### PR DESCRIPTION
**Pull request by queeksm**

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull request under review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Andres! 
 
#### Great job!  Wow, your project looks :+1: 

#### Navbar
Great that you use  the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links and Navigation bar have a fixed position (it sticks to the top part of the screen). 


- [ ]  But navbar should be made of nine different buttons with the Apple logo on the leftmost section and a search field on the rightmost section.
Screenshot from 2019-10-31 22-18-38

- [ ] Under navbar should be content. Friendly recommend please try to add this text.  It will make your project more perfect!

Screenshot from 2019-10-31 22-19-55



#### Bottom

* [ ] It contains four images which are links (to another articles or `#`)

Screenshot from 2019-10-31 22-37-43

#### Footer
Great that you use the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer! image


- [ ] Please check HTML markup with this validator https://validator.w3.org/#validate_by_upload. Now your project has Error.

### Make these changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @queeksm  :wave: 

The project is looking much better now. You are almost there. **Let's get rid of the horizontal scroll bar and then submit another code review**

image


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Review by suretrust — APPROVED** [review]
### Amazing job! Let's get this merged! :+1: 

_Good luck with your future projects and happy coding! :tada:_

**Pull request merged**
